# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/FPGA/H13D/constraints/Arty-S7-50-Rev-B-Master.xdc

# IP: ip/ila_1/ila_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] -quiet
